name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Package Helm Chart
        run: |
          cd charts/mychart
          helm package .
          mv mychart-*.tgz ../../

      - name: Update Helm Repo Index
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          mv ../mychart-*.tgz .
          helm repo index --url https://yourusername.github.io/your-repo/ --merge index.yaml .
          git add .
          git commit -m "Update Helm chart index"
          git push origin gh-pages

